language: rust
rust:
  - nightly

matrix:
  fast_finish: true

cache: cargo
sudo: false

# Install postgresql headers
addons:
  apt:
    packages:
      - libpq-dev

# Reduce email flood
notifications:
  email:
    on_success: never

# Only check develop for now
branches:
  only:
    - develop

before_install:
  - rustup component add clippy

script:
  - cargo check
  - cargo clippy
  - cargo test
