branches:
  only:
    - develop
language: rust
cache: cargo
rust:
  - nightly

sudo: false
addons:
  apt:
    packages:
      - libpq-dev

script:
  - cargo build
  - cargo test

notifications:
  email:
    on_success: never
