[package]
name = "kapitalist_backend"
version = "0.1.0"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/1wilkens/kapitalist"

[lib]
name = "kapitalist"
path = "src/lib.rs"

[[bin]]
name = "kapitalist"
path = "src/bin/main.rs"

[dependencies]
log = "0.4"
simplelog = "0.5"

dotenv = "0.11"

serde = "1.0"
serde_derive = "1.0"

chrono = { version = "0.4", features = ["serde"] }

diesel = { version = "1.2", features = ["chrono", "postgres"] }

actix-web = "=0.7.1"
futures = "0.1"

# Use upstream once a common ring version is established
#jsonwebtoken = { git = "https://github.com/1wilkens/jsonwebtoken.git" }
jsonwebtoken = "4.0"

# Use upstream once a common ring version is established
#ring-pwhash = { git = "https://github.com/1wilkens/ring-pwhash.git", rev = "5939162" }
ring-pwhash = "0.12"
