[package]
name = "kapitalist"
version = "0.1.0"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/1wilkens/kapitalist"

[dependencies]
dotenv = "0.11.0"

serde = "1.0.27"
serde_derive = "1.0.27"

chrono = { version = "0.4.0", features = ["serde"] }

diesel = { version = "1.1.1", features = ["chrono", "postgres", "r2d2"] }
diesel_codegen = "0.16.0"

#rocket = "0.3.6"
rocket = { git = "https://github.com/sergiobenitez/rocket.git", rev = "987f2d6" }
#rocket_codegen = "0.3.6"
rocket_codegen = { git = "https://github.com/sergiobenitez/rocket.git", rev = "987f2d6" }
#rocket_contrib = { version = "0.3.6", default_features = false, features = ["json"] }
rocket_contrib = { git = "https://github.com/sergiobenitez/rocket.git", rev = "987f2d6" }

# Use upstream once a common ring version is established
jsonwebtoken = { git = "https://github.com/1wilkens/jsonwebtoken.git" }

# Use upstream once a common ring version is established
ring-pwhash = { git = "https://github.com/1wilkens/ring-pwhash.git", rev = "5939162" }