[package]
name = "kapitalist_backend"
version = "0.1.0"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/1wilkens/kapitalist"

[lib]
name = "kapitalist"
path = "src/lib.rs"

[[bin]]
name = "kapitalist"
path = "src/bin/main.rs"

[dependencies]
log = "^0.4"
simplelog = "^0.5"

dotenv = "0.11.0"

serde = "1.0.62"
serde_derive = "1.0.62"

chrono = { version = "0.4.1", features = ["serde"] }

diesel = { version = "1.2.2", features = ["chrono", "postgres", "r2d2"] }

rocket = "0.3.11"
#rocket = { git = "https://github.com/sergiobenitez/rocket.git", rev = "3894e4e" }
rocket_codegen = "0.3.11"
#rocket_codegen = { git = "https://github.com/sergiobenitez/rocket.git", rev = "3894e4e" }
rocket_contrib = { version = "0.3.10", default_features = false, features = ["json"] }
#rocket_contrib = { git = "https://github.com/sergiobenitez/rocket.git", rev = "3894e4e" }

# Use upstream once a common ring version is established
#jsonwebtoken = { git = "https://github.com/1wilkens/jsonwebtoken.git" }
jsonwebtoken = "2.0.3"

# Use upstream once a common ring version is established
#ring-pwhash = { git = "https://github.com/1wilkens/ring-pwhash.git", rev = "5939162" }
ring-pwhash = "0.11.0"
