[package]
name = "kapitalist_backend"
version = "0.1.0"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/1wilkens/kapitalist"

[lib]
name = "kapitalist"
path = "src/lib.rs"

[[bin]]
name = "kapitalist"
path = "src/bin/main.rs"

[dependencies]
log = "0.4"
simplelog = "0.5"

dotenv = "0.13"

serde = "1.0"
serde_derive = "1.0"

chrono = { version = "0.4", features = ["serde"] }

diesel = { version = "1.3", default-features = false, features = ["32-column-tables", "chrono", "postgres"] }

actix = { version = "0.7", default-features = false }
actix-web = { version = "0.7", default-features = false }
futures = "0.1"

jsonwebtoken = "5.0"

libreauth = "0.10"
