version: "3"

services:
  api:
    container_name: kapitalist_api
    build: .
    image: kapitalistapp/backend:develop
    environment:
      # IP/port are already set per default
      KAPITALIST_HOST: 0.0.0.0
      KAPITALIST_PORT: 5454
      # Database connection string
      KAPITALIST_DB: postgres://kapitalist:supersecretpassword@db/kapitalist
      # JWT secret to sign auth tokens
      KAPITALIST_JWT_SECRET: supersecretsecret
    ports:
        - "127.0.0.1:5454:5454"
    networks:
      - net
    depends_on:
      - db

  db:
    container_name: kapitalist_db
    image: "postgres:11.1-alpine"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - net
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: kapitalist
      POSTGRES_USER: kapitalist
      POSTGRES_PASSWORD: supersecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

networks:
  net:

volumes:
  pgdata: {}
